// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // Supabase Edge Functions run on Deno, not Node. They import via `jsr:` and
    // use the `Deno` global, neither of which the app's toolchain resolves.
    // They are type-checked separately with `deno check`, not by this lint pass.
    //
    // `.expo/**` is generated by the typed-routes feature on every dev-server
    // start, so linting it produces warnings that change as Expo changes its
    // output. Generated code should not be linted.
    ignores: ["dist/*", "supabase/functions/**", ".expo/**"],
  },
]);
