/**
 * Fetch the Inter weights the site actually needs and emit the @font-face CSS.
 *
 * Google's CSS2 API returns one @font-face per (weight x unicode-range). Only
 * latin and latin-ext are kept: shipping Cyrillic, Greek and Vietnamese subsets
 * would triple the payload for characters this site never renders.
 */
import { writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = 'C:/Users/Sajidul Haque Sajid/Desktop/SELFLOW/sellflow/website';
const FONT_DIR = join(ROOT, 'public/assets/fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const WEIGHTS = [400, 500, 600, 700];

mkdirSync(FONT_DIR, { recursive: true });
for (const f of readdirSync(FONT_DIR)) rmSync(join(FONT_DIR, f));

const css = await (
  await fetch('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap', {
    headers: { 'user-agent': UA },
  })
).text();

const blocks = [...css.matchAll(/@font-face\s*\{[^}]+\}/g)].map((m) => m[0]);
const wanted = [];
for (const b of blocks) {
  const weight = Number(b.match(/font-weight:\s*(\d+)/)?.[1]);
  const range = b.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim() ?? '';
  const url = b.match(/url\((https:[^)]+)\)/)?.[1];
  // latin = U+0000-00FF, latin-ext = U+0100-02BA
  const subset = range.startsWith('U+0000-00FF') ? 'latin' : range.startsWith('U+0100-02BA') ? 'latin-ext' : null;
  if (url && subset && WEIGHTS.includes(weight)) wanted.push({ weight, subset, range, url });
}

// The css2 endpoint returns one file per subset, shared across every requested
// weight -- they are variable fonts. Dedupe by content hash and declare the
// full weight range once per subset, otherwise the same ~83 KB file would be
// downloaded four times over under four names.
const byHash = new Map();
for (const f of wanted) {
  if (byHash.has(f.url)) continue;
  const name = `inter-${f.subset}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'user-agent': UA } })).arrayBuffer());
  writeFileSync(join(FONT_DIR, name), buf);
  console.log(`  ${name.padEnd(26)} ${String(Math.round(buf.length / 1024)).padStart(4)} KB`);
  byHash.set(f.url, { name, ...f });
}

const faces = [];
for (const f of byHash.values()) {
  faces.push(
    [
      '@font-face {',
      "  font-family: 'Inter';",
      '  font-style: normal;',
      `  font-weight: ${Math.min(...WEIGHTS)} ${Math.max(...WEIGHTS)};`,
      '  font-display: swap;',
      `  src: url('../fonts/${f.name}') format('woff2');`,
      `  unicode-range: ${f.range};`,
      '}',
    ].join('\n')
  );
}

writeFileSync(
  join(ROOT, 'src/fonts.css'),
  `/* Inter, self-hosted. Generated by fetch-fonts.mjs -- do not edit by hand. */\n\n${faces.join('\n\n')}\n`
);
console.log(`\n  ${faces.length} @font-face rules -> src/fonts.css`);